import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./common/Header";
import Footer from "./common/Footer";
import ScrollToTopButton from "./ScrollToTopButton";
import Head from "next/head";

// Import Google Font (Inter)
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "William-Samuel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link href="https://fonts.cdnfonts.com/css/supra" rel="stylesheet" />
        <link
          rel="icon"
          type="image/png"
          href="/img/logo.webp"
        />
      </Head>
      <body
        className={`${inter.className} h-screen overflow-y-scroll scrollbar-thin scrollbar-thumb-rounded scrollbar-thumb-gray-500 scrollbar-track-gray-200`}
      >
        <Header />
        {children}
        <Footer />
        <ScrollToTopButton />
      </body>
    </html>
  );
}
